[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "@uniswap/v3-periphery/=lib/v3-periphery/", "@uniswap/v3-core/=lib/v3-core/", "@openzeppelin/contracts/=lib/openzeppelin/contracts/", "@openzeppelin/contracts/token/ERC721/IERC721Enumerable.sol=lib/openzeppelin/contracts/token/ERC721/extensions/IERC721Enumerable.sol", "@openzeppelin/contracts/token/ERC721/IERC721Metadata.sol=lib/openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol"]
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
